name: Docs
on: [push, workflow_dispatch]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pdoc)
        run: |
          python -m pip install --upgrade pip
          pip install pdoc

      - name: Generate HTML docs (pdoc)
        run: |
          mkdir -p build/docs
          echo "[INFO] Generando documentación con pdoc"
          pdoc . -o build/docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/docs
