name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        score=$(pylint $(git ls-files '*.py') --score=y --exit-zero | tee pylint.log | grep "Your code has been rated" | awk '{print $7}' | cut -d'/' -f1)
        echo "Pylint score: $score"
        # Compara la nota, exige >9
        if (( $(echo "$score < 9.0" | bc -l) )); then
          echo "❌ Pylint score too low: $score"
          exit 1
        else
          echo "✅ Pylint score is good: $score"
        fi

